# Generated by Django 5.1.6 on 2025-10-26 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_chatmessage_story_remove_post_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='anon_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
